
delete from items_seasons;
delete from item;

insert into item (name, category, enough_for_km, weight, notes) values 
('Backpack', 'STORAGE', 1500,  2.0, 'Storage for all equipment'),
('Hiking Boots', 'FOOTWEAR', 400, 1.5, 'Durable hiking boots for various terrains'),
('Winter Jacket', 'CLOTHING', 500, 2.0, 'Insulated jacket for cold weather'),
('Sunscreen', 'HEALTH_AND_SAFETY', 400,  0.2, 'Sunscreen for sun protection'),
('Trekking Poles', 'EQUIPMENT', 400, 0.8, 'Adjustable trekking poles for stability'),
('Sleeping Bag', 'SLEEP_SYSTEM', 600,  1.2, 'Lightweight sleeping bag for camping'),
('Water Bottle', 'HYDRATION',20,  0.5, 'Reusable water bottle for staying hydrated'),
('First Aid Kit', 'HEALTH_AND_SAFETY',1000, 0.7, 'Basic first aid supplies for emergencies'),
('Map and Compass', 'NAVIGATION', 600, 0.3, 'Navigation tools for finding your way'),
('Headlamp', 'LIGHTING', 350, 0.4, 'Headlamp for hands-free lighting'),
('Tent', 'SHELTER', 400, 2.5, 'Lightweight tent for overnight camping'),
('Power Bank', 'ELECTRONICS', 200, 0.3, 'Portable power bank for charging devices'),
('Dry Bags', 'STORAGE', 100, 0.6, 'Waterproof bags for keeping items dry'), 
('Hiking Socks', 'CLOTHING', 100, 0.1, 'Moisture-wicking socks for hiking'), 
('Camping Stove', 'COOKING', 300, 1.2, 'Portable stove for camping meals'), 
('Rain Jacket', 'CLOTHING', 500, 1.0, 'Waterproof jacket for rainy weather'),
('Sleeping Pad', 'SLEEP_SYSTEM', 500, 0.8, 'Inflatable sleeping pad for added comfort'),
('Multi-Tool', 'TOOLS', 1000,  0.5, 'Versatile multi-tool for various purposes'),
('Insect Repellent', 'HEALTH_AND_SAFETY', 400, 0.3, 'Repellent to protect against insects'),
('Emergency Whistle', 'HEALTH_AND_SAFETY', 2000, 0.1, 'Loud whistle for emergencies'),
('Portable Water Filter', 'HYDRATION', 600,  0.4, 'Filter for purifying water on the go'),
('Collapsible Water Container', 'HYDRATION', 400, 0.2, 'Collapsible container for water storage'),
('Trail Mix', 'FOOD', 40, 0.5, 'Energy-packed trail mix for snacks'),
('Travel Towel', 'HYGIENE', 600, 0.3, 'Quick-drying and compact towel for travel'),
('Bug Net', 'HEALTH_AND_SAFETY', 700, 0.5, 'Netting to protect against insects'),
('Travel Umbrella', 'SHELTER', 350, 0.5, 'Compact umbrella for unexpected rain');

delete from classificator;
INSERT INTO classificator (domain, code, meaning, description) VALUES
('SEASON', 'SUMMER', 'Summer', ''),
('SEASON', 'AUTUMN', 'Autumn', ''),
('SEASON', 'WINTER', 'Winter', ''),
('SEASON', 'SPRING', 'Spring', ''),
('SEASON', 'ALL_YEAR', 'All year', ''),
('RELIEF', 'FLAT', 'Flat terrain', ''),
('RELIEF', 'HILLY', 'Hilly terrain', ''),
('RELIEF', 'MOUNTAINOUS', 'Mountainous terrain', ''),
('RELIEF', 'FORESTED', 'Forested areas', ''),
('RELIEF', 'DESERT', 'Desert terrain', ''),
('RELIEF', 'COASTAL', 'Coastal areas', ''),
('RELIEF', 'URBAN', 'Urban environment', ''),
('RELIEF', 'RURAL', 'Rural landscape', ''),
('RELIEF', 'WILDERNESS', 'Wilderness areas', ''),
('CATEGORY', 'HYDRATION', 'Hydration', 'Items related to hydration for the trip'),
('CATEGORY', 'SHELTER', 'Shelter', 'Shelter items for the trip'),
('CATEGORY', 'FOOTWEAR', 'Footwear', 'Footwear suitable for the trip'),
('CATEGORY', 'CLOTHING', 'Clothing', 'Clothing items for the trip'),
('CATEGORY', 'HEALTH_AND_SAFETY', 'Health and Safety', 'Health and safety items for the trip'),
('CATEGORY', 'EQUIPMENT', 'Equipment', 'Equipment items for the trip'),
('CATEGORY', 'SLEEP_SYSTEM', 'Sleep System', 'Sleep system items for the trip'),
('CATEGORY', 'NAVIGATION', 'Navigation', 'Navigation items for the trip'),
('CATEGORY', 'COOKING', 'Cooking', 'Cooking items for the trip'),
('CATEGORY', 'LIGHTING', 'Lighting', 'Lighting items for the trip'),
('CATEGORY', 'ELECTRONICS', 'Electronics', 'Electronic items for the trip'),
('CATEGORY', 'STORAGE', 'Storage', 'Storage items for the trip'),
('CATEGORY', 'TOOLS', 'Tools', 'Tools items for the trip'),
('CATEGORY', 'OPTICS', 'Optics', 'Optics items for the trip'),
('CATEGORY', 'SAFETY', 'Safety', 'Safety items for the trip'),
('CATEGORY', 'FOOD', 'Food', 'Food items for the trip');


INSERT INTO items_seasons (item_id, classificator_id)
VALUES
  ((SELECT id FROM item WHERE category = 'STORAGE' AND name = 'Backpack') , (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')), 
  ((SELECT id FROM item WHERE category = 'FOOTWEAR' AND name = 'Hiking Boots'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'CLOTHING' AND name = 'Winter Jacket'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'WINTER')),
  ((SELECT id FROM item WHERE category = 'CLOTHING' AND name = 'Winter Jacket'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'AUTUMN')),
  ((SELECT id FROM item WHERE category = 'HEALTH_AND_SAFETY' AND name = 'Sunscreen'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'SUMMER')),
  ((SELECT id FROM item WHERE category = 'HEALTH_AND_SAFETY' AND name = 'Sunscreen'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'SPRING')),
  ((SELECT id FROM item WHERE category = 'EQUIPMENT' AND name = 'Trekking Poles'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'SPRING')),
  ((SELECT id FROM item WHERE category = 'EQUIPMENT' AND name = 'Trekking Poles'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'SUMMER')),
  ((SELECT id FROM item WHERE category = 'EQUIPMENT' AND name = 'Trekking Poles'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'AUTUMN')),
  ((SELECT id FROM item WHERE category = 'SLEEP_SYSTEM' AND name = 'Sleeping Bag'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'HYDRATION' AND name = 'Water Bottle'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'HEALTH_AND_SAFETY' AND name = 'First Aid Kit'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'NAVIGATION' AND name = 'Map and Compass'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'LIGHTING' AND name = 'Headlamp'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'SHELTER' AND name = 'Tent'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'ELECTRONICS' AND name = 'Power Bank'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'STORAGE' AND name = 'Dry Bags'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'AUTUMN')),
  ((SELECT id FROM item WHERE category = 'CLOTHING' AND name = 'Hiking Socks'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'COOKING' AND name = 'Camping Stove'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'CLOTHING' AND name = 'Rain Jacket'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'SPRING')),
  ((SELECT id FROM item WHERE category = 'CLOTHING' AND name = 'Rain Jacket'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'AUTUMN')),
  ((SELECT id FROM item WHERE category = 'CLOTHING' AND name = 'Rain Jacket'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'WINTER')),
  ((SELECT id FROM item WHERE category = 'SLEEP_SYSTEM' AND name = 'Sleeping Pad'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'WINTER')),
  ((SELECT id FROM item WHERE category = 'TOOLS' AND name = 'Multi-Tool'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'HEALTH_AND_SAFETY' AND name = 'Insect Repellent'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'SPRING')),
  ((SELECT id FROM item WHERE category = 'HEALTH_AND_SAFETY' AND name = 'Emergency Whistle'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'HYDRATION' AND name = 'Portable Water Filter'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'HYDRATION' AND name = 'Collapsible Water Container'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'FOOD' AND name = 'Trail Mix'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'HYGIENE' AND name = 'Travel Towel'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'ALL_YEAR')),
  ((SELECT id FROM item WHERE category = 'HEALTH_AND_SAFETY' AND name = 'Bug Net'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'SPRING')),
  ((SELECT id FROM item WHERE category = 'SHELTER' AND name = 'Travel Umbrella'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'SPRING')),
  ((SELECT id FROM item WHERE category = 'SHELTER' AND name = 'Travel Umbrella'), (SELECT id FROM classificator WHERE domain = 'SEASON' AND code = 'AUTUMN'));

/* Other way, but..
INSERT INTO items_seasons (item_id, season_code) VALUES
(1, 'SUMMER'),
(1, 'AUTUMN'),
(1, 'WINTER'),
(1, 'SPRING');
*/